[versions]
agp     = "8.5.0"
kotlin  = "2.0.0"
browser = "1.8.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-browser  = { module = "androidx.browser:browser", version.ref = "browser" }
junit             = { module = "junit:junit",             version = "4.13.2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
